// SPDX-License-Identifier: MIT
pragma solidity ^0.8.21;

// ─── Demo script — run against a local Anvil node ─────────────────────────────
//
//   # Terminal 1 — Anvil MUST be started with a raised code-size limit because
//   # the bb-generated HonkVerifier is 24642 bytes (66 bytes over EIP-170 default).
//   anvil --code-size-limit 50000
//
//   # Terminal 2
//   cd contracts
//   PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
//   forge script script/Demo.s.sol --rpc-url http://127.0.0.1:8545 \
//     --broadcast --disable-code-size-limit -vvvv
//
//   Note: --disable-code-size-limit bypasses forge's 24576-byte warning check.
//   Anvil's --code-size-limit 50000 bypasses the EVM enforcement on-chain.
//   Both are needed only for local dev. L2s (Arbitrum/Optimism) have no size limit.
//
// What this script does:
//   1. Deploy MockUSDC, HonkVerifier, ShieldVault
//   2. Company funds 3 employees (Alice $10k, Bob $8k, Carol $12k) via depositBatch
//   3. Alice claims her salary using a real ZK proof (generated by nargo + bb)
//   4. Double-spend attempt is caught and logged
// ─────────────────────────────────────────────────────────────────────────────

import "forge-std/Script.sol";
import "../src/MockUSDC.sol";
import "../src/ShieldVault.sol";
import "../src/Verifier.sol";

contract Demo is Script {
    address constant COMPANY = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
    address constant ALICE_RECIPIENT = 0x1234567890AbcdEF1234567890aBcdef12345678;

    // Prover.toml values for Alice
    bytes32 constant ALICE_COMMITMENT  = 0x2470043abc6987f84987373a60b134684f48b2a3e6a1331b1076188151fefc98;
    bytes32 constant ALICE_NULLIFIER   = 0x1396c32028ed63af7f97462b7193b33e22c57947eb4a066022edf33332919da5;
    bytes32 constant ALICE_PROOF_ROOT  = 0x1aa72582ab7693c6a5bdcf66dba56a536c92fd4d8199db4e096d751a540c872a;
    uint256 constant ALICE_AMOUNT      = 10000;

    MockUSDC    usdc;
    HonkVerifier honkVerifier;
    ShieldVault vault;

    uint256 constant COMPANY_KEY =
        0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80;

    function run() external {
        _deploy();
        _companyDeposit();
        _aliceWithdraw();
        _doubleSpendCheck();
        _printFinalState();
    }

    function _deploy() internal {
        vm.startBroadcast(COMPANY_KEY);
        usdc         = new MockUSDC();
        honkVerifier = new HonkVerifier();
        vault        = new ShieldVault(address(usdc), address(honkVerifier));
        vm.stopBroadcast();

        console.log("=== ShieldPay Demo ===");
        console.log("MockUSDC    :", address(usdc));
        console.log("Verifier    :", address(honkVerifier));
        console.log("ShieldVault :", address(vault));
    }

    function _companyDeposit() internal {
        uint256 total = (ALICE_AMOUNT + 8000 + 12000);

        vm.startBroadcast(COMPANY_KEY);
        usdc.mint(COMPANY, total * 1e6);
        usdc.approve(address(vault), total * 1e6);
        vm.stopBroadcast();

        // Compute Bob & Carol commitments (off-chain in production)
        bytes32 bobCommitment   = _computeCommitment(8000,  0xabcdef1234, MiMC.hash4(42, 0, 0, 0));
        bytes32 carolCommitment = _computeCommitment(12000, 0x9999999999, MiMC.hash4(99, 0, 0, 0));

        bytes32[] memory commitments = new bytes32[](3);
        uint256[] memory amounts     = new uint256[](3);

        commitments[0] = ALICE_COMMITMENT; amounts[0] = ALICE_AMOUNT;
        commitments[1] = bobCommitment;    amounts[1] = 8000;
        commitments[2] = carolCommitment;  amounts[2] = 12000;

        vm.startBroadcast(COMPANY_KEY);
        vault.depositBatch(commitments, amounts);
        vm.stopBroadcast();

        console.log("\n[Company] Deposited 3 notes");
        console.log("[Vault]  Leaves:", vault.nextIndex());
        console.log("[Vault]  Balance:", usdc.balanceOf(address(vault)) / 1e6, "USDC");
        console.log("[Vault]  Root:", uint256(vault.currentRoot()));
    }

    function _aliceWithdraw() internal {
        // Add the proof root via a real on-chain tx (our Prover.toml uses all-zero
        // siblings, so this root differs from what depositBatch produced — in
        // production the proof would be generated against the actual tree root).
        vm.startBroadcast(COMPANY_KEY);
        vault.addKnownRoot(ALICE_PROOF_ROOT);
        vm.stopBroadcast();

        bytes memory proof = vm.readFileBinary("../circuits/target/alice_proof/proof");

        console.log("\n[Alice] Proof size:", proof.length, "bytes");
        console.log("[Alice] Claiming:", ALICE_AMOUNT, "USDC");

        vm.startBroadcast(COMPANY_KEY); // relayer submits tx
        vault.withdrawToStealth(proof, ALICE_PROOF_ROOT, ALICE_NULLIFIER, ALICE_RECIPIENT, ALICE_AMOUNT);
        vm.stopBroadcast();

        console.log("[Alice] Received:", usdc.balanceOf(ALICE_RECIPIENT) / 1e6, "USDC");
    }

    function _doubleSpendCheck() internal {
        bytes memory proof = vm.readFileBinary("../circuits/target/alice_proof/proof");

        // Use vm.prank (no broadcast) so the revert is caught locally without
        // producing a failed on-chain tx.
        vm.prank(COMPANY);
        try vault.withdrawToStealth(proof, ALICE_PROOF_ROOT, ALICE_NULLIFIER, ALICE_RECIPIENT, ALICE_AMOUNT) {
            console.log("\n[ERROR] Double-spend should have reverted!");
        } catch Error(string memory reason) {
            console.log("\n[OK] Double-spend reverted:", reason);
        }
    }

    function _printFinalState() internal view {
        console.log("\n=== Final State ===");
        console.log("Alice balance:", usdc.balanceOf(ALICE_RECIPIENT) / 1e6, "USDC");
        console.log("Vault balance:", usdc.balanceOf(address(vault)) / 1e6, "USDC");
        console.log("Nullifier used:", vault.isNullifierSpent(ALICE_NULLIFIER));
    }

    function _computeCommitment(uint256 amount, uint256 nonce, uint256 pubkey)
        internal pure returns (bytes32)
    {
        return bytes32(MiMC.hash4(amount, nonce, pubkey, 0));
    }
}
